import { PharmacySettings, User, Supplier, Category } from '../types';

export const demoPharmacySettings: PharmacySettings = {
  pharmacyName: "HealthPlus Pharmacy",
  licenseNumber: "HP-ACCRA-2024-GH",
  address: "Plot 42 Liberation Road, Airport Residential Area, Accra, Ghana",
  phone: "+233 20 000 0000",
  email: "demo@healthpluspharmacy.example",
  website: "https://healthpluspharmacy.example",
  vatNumber: "GH-TIN-9948201",
  currency: "GHS",
  currencySymbol: "GH₵",
  country: "Ghana",
  countryCode: "GH",
  language: "English",
  languageCode: "en-GH",
  timezone: "Africa/Accra",
  vatRate: 15.0,
  invoicePrefix: "INV",
  lowStockThreshold: 15,
  expiryWarningDays: 90,
  enablePrescriptionAlert: true,
  enableLoyaltyProgram: true,
  receiptHeaderNotice: "HealthPlus Pharmacy • Quality Healthcare You Can Trust • Accra, Ghana",
  receiptFooterNotice: "Thank you for choosing HealthPlus Pharmacy! Valid Rx required for prescription medicines. Call +233 20 000 0000 for emergency refills.",
  isCompanyConfigured: true
};

export const demoUsers: User[] = [
  {
    id: "usr-demo-owner",
    name: "John Mensah",
    email: "john.mensah@healthpluspharmacy.example",
    role: "Pharmacy Owner",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0001",
    status: "Active"
  },
  {
    id: "usr-demo-admin",
    name: "Michael Osei",
    email: "michael.osei@healthpluspharmacy.example",
    role: "Administrator",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0002",
    status: "Active"
  },
  {
    id: "usr-demo-pharmacist",
    name: "Ama Boateng",
    email: "ama.boateng@healthpluspharmacy.example",
    role: "Pharmacist",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0003",
    status: "Active"
  },
  {
    id: "usr-demo-cashier",
    name: "Daniel Owusu",
    email: "daniel.owusu@healthpluspharmacy.example",
    role: "Cashier",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0004",
    status: "Active"
  },
  {
    id: "usr-demo-manager",
    name: "Grace Asante",
    email: "grace.asante@healthpluspharmacy.example",
    role: "Store Manager",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0005",
    status: "Active"
  },
  {
    id: "usr-demo-accountant",
    name: "Kwesi Appiah",
    email: "kwesi.appiah@healthpluspharmacy.example",
    role: "Accountant",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&q=80",
    phone: "+233 20 111 0006",
    status: "Active"
  }
];

export const demoSuppliers: Supplier[] = [
  {
    id: "sup-gh-1",
    name: "MedCare Distributors Ghana",
    contactPerson: "Kwadwo Twumasi",
    phone: "+233 30 222 1001",
    email: "orders@medcareghana.example",
    address: "Graphic Road, Industrial Area, Accra, Ghana",
    category: "Pharmaceutical Wholesaler",
    paymentTerms: "Net 30",
    taxId: "GH-TIN-881023",
    notes: "Main distributor for antibiotics, cardiac and essential medicines.",
    totalPurchased: 145000.00,
    balanceOwed: 12500.00,
    status: "Active"
  },
  {
    id: "sup-gh-2",
    name: "Ghana Health Supplies Ltd",
    contactPerson: "Evelyn Addy",
    phone: "+233 30 222 1002",
    email: "supplies@ghanahealth.example",
    address: "North Industrial Area, Kaneshie, Accra, Ghana",
    category: "Wholesaler & Importer",
    paymentTerms: "Net 30",
    taxId: "GH-TIN-771924",
    notes: "Key importer of syrups, paediatric lines and vaccines.",
    totalPurchased: 98000.00,
    balanceOwed: 0.00,
    status: "Active"
  },
  {
    id: "sup-gh-3",
    name: "Prime Pharma Ltd",
    contactPerson: "Dr. Seth Mensah",
    phone: "+233 30 222 1003",
    email: "sales@primepharma.example",
    address: "Spintex Road, Near Coca-Cola Roundabout, Accra, Ghana",
    category: "Manufacturer Direct",
    paymentTerms: "Net 15",
    taxId: "GH-TIN-662810",
    notes: "Local pharmaceutical manufacturer for paracetamol and pain formulations.",
    totalPurchased: 84000.00,
    balanceOwed: 7400.00,
    status: "Active"
  },
  {
    id: "sup-gh-4",
    name: "Accra Medical Distributors",
    contactPerson: "Vida Osei",
    phone: "+233 30 222 1004",
    email: "info@accramedical.example",
    address: "Ring Road Central, Adabraka, Accra, Ghana",
    category: "Pharmaceutical Wholesaler",
    paymentTerms: "Net 45",
    taxId: "GH-TIN-553901",
    notes: "High-volume distributor with overdue credit grace period.",
    totalPurchased: 112000.00,
    balanceOwed: 18200.00,
    status: "Active"
  },
  {
    id: "sup-gh-5",
    name: "HealthLink Supplies",
    contactPerson: "Francis Baidoo",
    phone: "+233 30 222 1005",
    email: "contact@healthlink.example",
    address: "Osu Badu Street, Dzorwulu, Accra, Ghana",
    category: "Consumables & Diagnostics",
    paymentTerms: "Immediate",
    taxId: "GH-TIN-448102",
    notes: "Rapid delivery on medical diagnostic strips and pregnancy kits.",
    totalPurchased: 45000.00,
    balanceOwed: 0.00,
    status: "Active"
  },
  {
    id: "sup-gh-6",
    name: "West Africa Pharma Wholesale",
    contactPerson: "Patricia Quaye",
    phone: "+233 30 222 1006",
    email: "procurement@wapharm.example",
    address: "Harbour Commercial Area, Community 1, Tema, Ghana",
    category: "Generic Drugs Importer",
    paymentTerms: "Net 30",
    taxId: "GH-TIN-332918",
    notes: "Direct container deliveries for generic formulations.",
    totalPurchased: 168000.00,
    balanceOwed: 24500.00,
    status: "Active"
  },
  {
    id: "sup-gh-7",
    name: "CarePoint Distributors",
    contactPerson: "Emmanuel Agyei",
    phone: "+233 30 222 1007",
    email: "orders@carepoint.example",
    address: "Airport Commercial Center, Accra, Ghana",
    category: "Specialty Pharmaceuticals",
    paymentTerms: "Net 15",
    taxId: "GH-TIN-221904",
    notes: "Supplies cold-chain insulins, inhalers and eye drops.",
    totalPurchased: 76000.00,
    balanceOwed: 4200.00,
    status: "Active"
  },
  {
    id: "sup-gh-8",
    name: "MediSource Ghana",
    contactPerson: "Abena Koranteng",
    phone: "+233 30 222 1008",
    email: "service@medisourcegh.example",
    address: "Achimota Transport Terminal Road, Accra, Ghana",
    category: "Vitamins & Nutritional",
    paymentTerms: "Net 30",
    taxId: "GH-TIN-110293",
    notes: "Exclusive distributor of wellness supplements and skin formulations.",
    totalPurchased: 62000.00,
    balanceOwed: 9500.00,
    status: "Active"
  },
  {
    id: "sup-gh-9",
    name: "Apex Pharma Wholesale",
    contactPerson: "Kofi Owusu-Ansah",
    phone: "+233 30 222 1009",
    email: "kofi@apexpharma.example",
    address: "Cantonments Road, Osu, Accra, Ghana",
    category: "Dermatological & OTC",
    paymentTerms: "COD",
    taxId: "GH-TIN-908124",
    notes: "Fast delivery for over-the-counter and skincare inventory.",
    totalPurchased: 39000.00,
    balanceOwed: 0.00,
    status: "Active"
  },
  {
    id: "sup-gh-10",
    name: "Atlantic Medicals Ghana",
    contactPerson: "Nana Yaa Donkor",
    phone: "+233 30 222 1010",
    email: "orders@atlanticmedicals.example",
    address: "East Legon Boundary Road, Accra, Ghana",
    category: "Multivitamins & Baby Care",
    paymentTerms: "Net 30",
    taxId: "GH-TIN-817290",
    notes: "Supplier of premium infant nutrition and prenatal multivitamins.",
    totalPurchased: 53000.00,
    balanceOwed: 5800.00,
    status: "Active"
  }
];

export const demoCategories: Category[] = [
  { id: "cat-vitamins", name: "Vitamins & Supplements", description: "Nutritional supplements, multivitamins and immunity boosters" },
  { id: "cat-cough-cold", name: "Cough, Cold & Flu", description: "Decongestants, cough syrups, antihistamines and flu relief" },
  { id: "cat-pain-relief", name: "Pain Relief", description: "Analgesics, anti-inflammatories, fever reducers and muscle relief" },
  { id: "cat-mens-health", name: "Men's Health", description: "Prostate care, testosterone support, hair retention and vitality" },
  { id: "cat-womens-health", name: "Women's Health", description: "Hormone balance, menopause relief, menstrual care and wellness" },
  { id: "cat-pregnancy", name: "Conception & Pregnancy", description: "Prenatal vitamins, folic acid, fertility tests and maternity care" },
  { id: "cat-baby-child", name: "Baby & Child Health", description: "Pediatric syrups, colic drops, teething gel and child nutrition" },
  { id: "cat-diet-fitness", name: "Diet & Fitness", description: "Protein powders, weight management, hydration and energy" },
  { id: "cat-sexual-wellness", name: "Sexual Wellness", description: "Intimate health, reproductive care and wellness products" },
  { id: "cat-beauty-supplements", name: "Beauty Supplements", description: "Collagen, biotin, skin radiance and hair & nail nutrients" },
  { id: "cat-antibiotics", name: "Antibiotics", description: "Bacterial infection treatments and broad-spectrum antimicrobials" },
  { id: "cat-cardiovascular", name: "Cardiovascular", description: "Hypertension, cholesterol and cardiac wellness" },
  { id: "cat-diabetes", name: "Diabetes Care", description: "Insulins, oral hypoglycemics and blood glucose test strips" },
  { id: "cat-gastro", name: "Gastrointestinal", description: "Antacids, proton pump inhibitors and digestive aid" }
];
