import { Medicine } from '../types';

export const demoMedicines: Medicine[] = [
  // 1. Vitamins & Supplements
  {
    id: "med-gh-01",
    barcode: "60010010001",
    name: "Wellman Original Multivitamin",
    genericName: "Micronutrients with Ginseng & CoQ10",
    category: "Vitamins & Supplements",
    brand: "Vitabiotics",
    dosageForm: "Tablet",
    strength: "30 Tablets",
    batchNumber: "BN-2026-WM01",
    manufactureDate: "2025-01-10",
    expiryDate: "2027-04-30",
    purchasePrice: 95.00,
    sellingPrice: 145.00,
    stockQuantity: 42,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 1 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock",
    description: "Advanced daily micronutrient formula for men.",
    sideEffects: "Rare mild stomach upset."
  },
  {
    id: "med-gh-02",
    barcode: "60010010002",
    name: "Wellwoman Original Multivitamin",
    genericName: "Vitamins B6, B12, Iron & Evening Primrose",
    category: "Vitamins & Supplements",
    brand: "Vitabiotics",
    dosageForm: "Capsule",
    strength: "30 Capsules",
    batchNumber: "BN-2026-WW02",
    manufactureDate: "2025-02-15",
    expiryDate: "2027-05-30",
    purchasePrice: 98.00,
    sellingPrice: 150.00,
    stockQuantity: 38,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 1 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-03",
    barcode: "60010010003",
    name: "Seven Seas Cod Liver Oil Plus Omega-3",
    genericName: "Omega-3 with Vitamin D & E",
    category: "Vitamins & Supplements",
    brand: "Seven Seas",
    dosageForm: "Capsule",
    strength: "100 Capsules",
    batchNumber: "BN-2025-SS03",
    manufactureDate: "2024-06-01",
    expiryDate: "2026-10-15", // Expiring soon in ~1 month
    purchasePrice: 85.00,
    sellingPrice: 130.00,
    stockQuantity: 12,
    minReorderLevel: 15,
    unit: "Bottle",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 1 - Shelf C",
    isPrescriptionRequired: false,
    status: "Expiring Soon"
  },
  {
    id: "med-gh-04",
    barcode: "60010010004",
    name: "Redoxon Vitamin C + Zinc Effervescent",
    genericName: "Ascorbic Acid 1000mg + Zinc 10mg",
    category: "Vitamins & Supplements",
    brand: "Bayer",
    dosageForm: "Effervescent Tablet",
    strength: "1000mg",
    batchNumber: "BN-2025-RX04",
    manufactureDate: "2024-11-01",
    expiryDate: "2027-02-28",
    purchasePrice: 42.00,
    sellingPrice: 65.00,
    stockQuantity: 8, // Low Stock alert
    minReorderLevel: 20,
    unit: "Tube",
    supplierId: "sup-gh-10",
    supplierName: "Atlantic Medicals Ghana",
    locationRack: "Aisle 1 - Shelf A",
    isPrescriptionRequired: false,
    status: "Low Stock"
  },
  {
    id: "med-gh-05",
    barcode: "60010010005",
    name: "Nature's Field Calcium, Magnesium & Zinc",
    genericName: "Calcium 1000mg, Magnesium 400mg, Zinc 15mg",
    category: "Vitamins & Supplements",
    brand: "Nature's Field",
    dosageForm: "Tablet",
    strength: "100 Tablets",
    batchNumber: "BN-2024-NF05",
    manufactureDate: "2024-01-10",
    expiryDate: "2026-08-30", // Already Expired
    purchasePrice: 60.00,
    sellingPrice: 95.00,
    stockQuantity: 5,
    minReorderLevel: 10,
    unit: "Bottle",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Quarantine Bin - Expired",
    isPrescriptionRequired: false,
    status: "Expired"
  },

  // 2. Cough, Cold & Flu
  {
    id: "med-gh-06",
    barcode: "60010010006",
    name: "Benylin 4 Flu Liquid",
    genericName: "Diphenhydramine, Pseudoephedrine, Paracetamol",
    category: "Cough, Cold & Flu",
    brand: "Johnson & Johnson",
    dosageForm: "Syrup",
    strength: "100ml",
    batchNumber: "BN-2025-BN06",
    manufactureDate: "2025-03-01",
    expiryDate: "2027-08-31",
    purchasePrice: 38.00,
    sellingPrice: 60.00,
    stockQuantity: 55,
    minReorderLevel: 20,
    unit: "Bottle",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Aisle 2 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-07",
    barcode: "60010010007",
    name: "Fludrex Tablets",
    genericName: "Paracetamol, Pseudoephedrine, Chlorpheniramine",
    category: "Cough, Cold & Flu",
    brand: "Kuwait Saudi",
    dosageForm: "Tablet",
    strength: "24 Tablets",
    batchNumber: "BN-2025-FL07",
    manufactureDate: "2025-01-20",
    expiryDate: "2027-06-30",
    purchasePrice: 22.00,
    sellingPrice: 35.00,
    stockQuantity: 74,
    minReorderLevel: 25,
    unit: "Box",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Aisle 2 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-08",
    barcode: "60010010008",
    name: "Prospan Ivy Leaf Cough Syrup",
    genericName: "Hedera Helix Extract",
    category: "Cough, Cold & Flu",
    brand: "Engelhard",
    dosageForm: "Syrup",
    strength: "100ml",
    batchNumber: "BN-2025-PS08",
    manufactureDate: "2025-02-10",
    expiryDate: "2027-07-31",
    purchasePrice: 58.00,
    sellingPrice: 90.00,
    stockQuantity: 0, // Out of Stock
    minReorderLevel: 15,
    unit: "Bottle",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Aisle 2 - Shelf A",
    isPrescriptionRequired: false,
    status: "Out of Stock"
  },
  {
    id: "med-gh-09",
    barcode: "60010010009",
    name: "Strepsils Honey & Lemon Lozenges",
    genericName: "Dichlorobenzyl Alcohol & Amylmetacresol",
    category: "Cough, Cold & Flu",
    brand: "Reckitt Benckiser",
    dosageForm: "Lozenge",
    strength: "24 Lozenges",
    batchNumber: "BN-2025-ST09",
    manufactureDate: "2025-04-01",
    expiryDate: "2027-10-31",
    purchasePrice: 28.00,
    sellingPrice: 45.00,
    stockQuantity: 62,
    minReorderLevel: 20,
    unit: "Pack",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Counter Display - Shelf 1",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-10",
    barcode: "60010010010",
    name: "Otrivin Adult 0.1% Nasal Spray",
    genericName: "Xylometazoline Hydrochloride",
    category: "Cough, Cold & Flu",
    brand: "GSK",
    dosageForm: "Spray",
    strength: "10ml",
    batchNumber: "BN-2025-OT10",
    manufactureDate: "2024-09-01",
    expiryDate: "2026-11-30", // Expiring soon
    purchasePrice: 35.00,
    sellingPrice: 55.00,
    stockQuantity: 7, // Low Stock
    minReorderLevel: 12,
    unit: "Bottle",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 2 - Shelf C",
    isPrescriptionRequired: false,
    status: "Low Stock"
  },

  // 3. Pain Relief
  {
    id: "med-gh-11",
    barcode: "60010010011",
    name: "Panadol Extra Tablets",
    genericName: "Paracetamol 500mg + Caffeine 65mg",
    category: "Pain Relief",
    brand: "GSK",
    dosageForm: "Tablet",
    strength: "500mg/65mg",
    batchNumber: "BN-2026-PE11",
    manufactureDate: "2025-05-15",
    expiryDate: "2028-04-30",
    purchasePrice: 18.00,
    sellingPrice: 28.00,
    stockQuantity: 180, // High stock, fast mover
    minReorderLevel: 50,
    unit: "Pack",
    supplierId: "sup-gh-3",
    supplierName: "Prime Pharma Ltd",
    locationRack: "Aisle 3 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-12",
    barcode: "60010010012",
    name: "Voltaren Emulgel Extra Strength",
    genericName: "Diclofenac Diethylamine 2.32%",
    category: "Pain Relief",
    brand: "GSK Consumer",
    dosageForm: "Gel",
    strength: "100g",
    batchNumber: "BN-2025-VE12",
    manufactureDate: "2025-01-10",
    expiryDate: "2027-03-31",
    purchasePrice: 65.00,
    sellingPrice: 98.00,
    stockQuantity: 28,
    minReorderLevel: 15,
    unit: "Tube",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 3 - Shelf C",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-13",
    barcode: "60010010013",
    name: "Ibuprofen Suspension 100mg/5ml",
    genericName: "Ibuprofen Pediatric",
    category: "Pain Relief",
    brand: "Ernest Chemists",
    dosageForm: "Syrup",
    strength: "100ml",
    batchNumber: "BN-2025-IB13",
    manufactureDate: "2025-02-18",
    expiryDate: "2027-05-30",
    purchasePrice: 16.00,
    sellingPrice: 26.00,
    stockQuantity: 46,
    minReorderLevel: 20,
    unit: "Bottle",
    supplierId: "sup-gh-3",
    supplierName: "Prime Pharma Ltd",
    locationRack: "Aisle 3 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-14",
    barcode: "60010010014",
    name: "Tramadol Capsules 50mg",
    genericName: "Tramadol Hydrochloride",
    category: "Pain Relief",
    brand: "Medochemie",
    dosageForm: "Capsule",
    strength: "50mg",
    batchNumber: "BN-2025-TR14",
    manufactureDate: "2025-01-12",
    expiryDate: "2027-06-30",
    purchasePrice: 25.00,
    sellingPrice: 42.00,
    stockQuantity: 14,
    minReorderLevel: 15,
    unit: "Strip",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Controlled Drugs Safe",
    isPrescriptionRequired: true,
    status: "Low Stock"
  },
  {
    id: "med-gh-15",
    barcode: "60010010015",
    name: "Deep Heat Rub",
    genericName: "Menthol & Methyl Salicylate",
    category: "Pain Relief",
    brand: "Mentholatum",
    dosageForm: "Cream",
    strength: "67g",
    batchNumber: "BN-2025-DH15",
    manufactureDate: "2024-10-01",
    expiryDate: "2027-01-31",
    purchasePrice: 32.00,
    sellingPrice: 50.00,
    stockQuantity: 34,
    minReorderLevel: 10,
    unit: "Tube",
    supplierId: "sup-gh-9",
    supplierName: "Apex Pharma Wholesale",
    locationRack: "Aisle 3 - Shelf D",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 4. Men's Health
  {
    id: "med-gh-16",
    barcode: "60010010016",
    name: "Prostamol Uno Softgels",
    genericName: "Serenoa Repens (Saw Palmetto Extract) 320mg",
    category: "Men's Health",
    brand: "Berlin-Chemie",
    dosageForm: "Capsule",
    strength: "320mg",
    batchNumber: "BN-2025-PU16",
    manufactureDate: "2025-02-01",
    expiryDate: "2027-08-31",
    purchasePrice: 110.00,
    sellingPrice: 165.00,
    stockQuantity: 24,
    minReorderLevel: 10,
    unit: "Box",
    supplierId: "sup-gh-7",
    supplierName: "CarePoint Distributors",
    locationRack: "Aisle 4 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-17",
    barcode: "60010010017",
    name: "Wellman Prostace Tablets",
    genericName: "Prostate Support Complex with Zinc & Lycopene",
    category: "Men's Health",
    brand: "Vitabiotics",
    dosageForm: "Tablet",
    strength: "60 Tablets",
    batchNumber: "BN-2025-WP17",
    manufactureDate: "2025-03-15",
    expiryDate: "2027-09-30",
    purchasePrice: 140.00,
    sellingPrice: 210.00,
    stockQuantity: 18,
    minReorderLevel: 8,
    unit: "Box",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 4 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-18",
    barcode: "60010010018",
    name: "Regaine for Men Extra Strength Foam 5%",
    genericName: "Minoxidil Topical 5%",
    category: "Men's Health",
    brand: "Johnson & Johnson",
    dosageForm: "Foam",
    strength: "73ml",
    batchNumber: "BN-2025-RG18",
    manufactureDate: "2024-11-20",
    expiryDate: "2026-12-15",
    purchasePrice: 220.00,
    sellingPrice: 320.00,
    stockQuantity: 9,
    minReorderLevel: 5,
    unit: "Bottle",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 4 - Shelf C",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 5. Women's Health
  {
    id: "med-gh-19",
    barcode: "60010010019",
    name: "Menopace Plus Tablets",
    genericName: "Botanical Extracts with Isoflavones & Vitamins",
    category: "Women's Health",
    brand: "Vitabiotics",
    dosageForm: "Tablet",
    strength: "56 Tablets",
    batchNumber: "BN-2025-MP19",
    manufactureDate: "2025-01-25",
    expiryDate: "2027-05-31",
    purchasePrice: 135.00,
    sellingPrice: 195.00,
    stockQuantity: 21,
    minReorderLevel: 10,
    unit: "Box",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Aisle 5 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-20",
    barcode: "60010010020",
    name: "Canesten Oral & External Cream Duo",
    genericName: "Fluconazole 150mg + Clotrimazole 2% Cream",
    category: "Women's Health",
    brand: "Bayer",
    dosageForm: "Combination Pack",
    strength: "1 Capsule + 10g Cream",
    batchNumber: "BN-2025-CN20",
    manufactureDate: "2025-03-01",
    expiryDate: "2027-06-30",
    purchasePrice: 62.00,
    sellingPrice: 95.00,
    stockQuantity: 32,
    minReorderLevel: 12,
    unit: "Pack",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 5 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-21",
    barcode: "60010010021",
    name: "Primolut N Tablets 5mg",
    genericName: "Norethisterone 5mg",
    category: "Women's Health",
    brand: "Bayer",
    dosageForm: "Tablet",
    strength: "30 Tablets",
    batchNumber: "BN-2025-PN21",
    manufactureDate: "2025-02-12",
    expiryDate: "2027-04-30",
    purchasePrice: 48.00,
    sellingPrice: 75.00,
    stockQuantity: 15,
    minReorderLevel: 10,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 5 - Shelf C",
    isPrescriptionRequired: true,
    status: "In Stock"
  },

  // 6. Conception & Pregnancy
  {
    id: "med-gh-22",
    barcode: "60010010022",
    name: "Pregnacare Plus Omega-3",
    genericName: "Prenatal Multivitamin with DHA & Folic Acid",
    category: "Conception & Pregnancy",
    brand: "Vitabiotics",
    dosageForm: "Dual Pack",
    strength: "56 Tablets/Capsules",
    batchNumber: "BN-2026-PP22",
    manufactureDate: "2025-04-01",
    expiryDate: "2027-11-30",
    purchasePrice: 120.00,
    sellingPrice: 180.00,
    stockQuantity: 40,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-10",
    supplierName: "Atlantic Medicals Ghana",
    locationRack: "Aisle 6 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-23",
    barcode: "60010010023",
    name: "Clearblue Digital Pregnancy Test",
    genericName: "hCG Digital Immunoassay with Weeks Indicator",
    category: "Conception & Pregnancy",
    brand: "Clearblue",
    dosageForm: "Test Device",
    strength: "2 Tests Pack",
    batchNumber: "BN-2025-CB23",
    manufactureDate: "2025-02-10",
    expiryDate: "2027-01-31",
    purchasePrice: 85.00,
    sellingPrice: 135.00,
    stockQuantity: 26,
    minReorderLevel: 10,
    unit: "Box",
    supplierId: "sup-gh-5",
    supplierName: "HealthLink Supplies",
    locationRack: "Aisle 6 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-24",
    barcode: "60010010024",
    name: "Folic Acid Tablets 5mg",
    genericName: "Folic Acid BP",
    category: "Conception & Pregnancy",
    brand: "Ernest Chemists",
    dosageForm: "Tablet",
    strength: "5mg",
    batchNumber: "BN-2025-FA24",
    manufactureDate: "2025-01-05",
    expiryDate: "2028-01-31",
    purchasePrice: 8.00,
    sellingPrice: 15.00,
    stockQuantity: 120,
    minReorderLevel: 30,
    unit: "Bottle",
    supplierId: "sup-gh-3",
    supplierName: "Prime Pharma Ltd",
    locationRack: "Aisle 6 - Shelf C",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 7. Baby & Child Health
  {
    id: "med-gh-25",
    barcode: "60010010025",
    name: "Calpol Infant Suspension 120mg/5ml",
    genericName: "Paracetamol Infant",
    category: "Baby & Child Health",
    brand: "Johnson & Johnson",
    dosageForm: "Suspension",
    strength: "100ml",
    batchNumber: "BN-2025-CP25",
    manufactureDate: "2025-03-20",
    expiryDate: "2027-08-31",
    purchasePrice: 32.00,
    sellingPrice: 50.00,
    stockQuantity: 48,
    minReorderLevel: 20,
    unit: "Bottle",
    supplierId: "sup-gh-10",
    supplierName: "Atlantic Medicals Ghana",
    locationRack: "Aisle 7 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-26",
    barcode: "60010010026",
    name: "Infacol Colic Relief Drops",
    genericName: "Simeticone 40mg/ml",
    category: "Baby & Child Health",
    brand: "Infacol",
    dosageForm: "Drops",
    strength: "50ml",
    batchNumber: "BN-2025-IF26",
    manufactureDate: "2025-01-15",
    expiryDate: "2027-04-30",
    purchasePrice: 45.00,
    sellingPrice: 70.00,
    stockQuantity: 19,
    minReorderLevel: 10,
    unit: "Bottle",
    supplierId: "sup-gh-10",
    supplierName: "Atlantic Medicals Ghana",
    locationRack: "Aisle 7 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-27",
    barcode: "60010010027",
    name: "Bonjela Teething Gel",
    genericName: "Choline Salicylate & Cetalkonium Chloride",
    category: "Baby & Child Health",
    brand: "Reckitt",
    dosageForm: "Gel",
    strength: "15g",
    batchNumber: "BN-2025-BJ27",
    manufactureDate: "2024-10-10",
    expiryDate: "2026-10-31", // Expiring soon
    purchasePrice: 26.00,
    sellingPrice: 42.00,
    stockQuantity: 8,
    minReorderLevel: 10,
    unit: "Tube",
    supplierId: "sup-gh-10",
    supplierName: "Atlantic Medicals Ghana",
    locationRack: "Aisle 7 - Shelf C",
    isPrescriptionRequired: false,
    status: "Expiring Soon"
  },

  // 8. Diet & Fitness
  {
    id: "med-gh-28",
    barcode: "60010010028",
    name: "Optimum Nutrition Gold Standard 100% Whey",
    genericName: "Whey Protein Isolate & Peptides",
    category: "Diet & Fitness",
    brand: "Optimum Nutrition",
    dosageForm: "Powder",
    strength: "2 lbs (907g)",
    batchNumber: "BN-2025-ON28",
    manufactureDate: "2025-02-01",
    expiryDate: "2027-06-30",
    purchasePrice: 380.00,
    sellingPrice: 550.00,
    stockQuantity: 15,
    minReorderLevel: 5,
    unit: "Tub",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Fitness Display - Top",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-29",
    barcode: "60010010029",
    name: "Dioralyte Blackcurrant Rehydration Sachets",
    genericName: "Oral Rehydration Salts (WHO Formula)",
    category: "Diet & Fitness",
    brand: "Sanofi",
    dosageForm: "Powder Sachet",
    strength: "6 Sachets",
    batchNumber: "BN-2025-DL29",
    manufactureDate: "2025-03-01",
    expiryDate: "2027-09-30",
    purchasePrice: 28.00,
    sellingPrice: 45.00,
    stockQuantity: 36,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Aisle 8 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 9. Sexual Wellness
  {
    id: "med-gh-30",
    barcode: "60010010030",
    name: "Durex Extra Safe Condoms",
    genericName: "Latex Lubricated Barrier Contraceptive",
    category: "Sexual Wellness",
    brand: "Reckitt",
    dosageForm: "Prophylactic",
    strength: "12 Pack",
    batchNumber: "BN-2025-DX30",
    manufactureDate: "2025-01-10",
    expiryDate: "2029-12-31",
    purchasePrice: 35.00,
    sellingPrice: 55.00,
    stockQuantity: 82,
    minReorderLevel: 25,
    unit: "Pack",
    supplierId: "sup-gh-5",
    supplierName: "HealthLink Supplies",
    locationRack: "Aisle 9 - Shelf A",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-31",
    barcode: "60010010031",
    name: "Postinor-2 Emergency Contraceptive",
    genericName: "Levonorgestrel 0.75mg",
    category: "Sexual Wellness",
    brand: "Gedeon Richter",
    dosageForm: "Tablet",
    strength: "2 Tablets",
    batchNumber: "BN-2026-P231",
    manufactureDate: "2025-04-12",
    expiryDate: "2028-03-31",
    purchasePrice: 22.00,
    sellingPrice: 38.00,
    stockQuantity: 65,
    minReorderLevel: 20,
    unit: "Pack",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Pharmacist Dispensing Desk",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 10. Beauty Supplements
  {
    id: "med-gh-32",
    barcode: "60010010032",
    name: "Perfectil Platinum Collagen Skin Drink",
    genericName: "Hydrolyzed Marine Collagen with CoQ10",
    category: "Beauty Supplements",
    brand: "Vitabiotics",
    dosageForm: "Liquid Bottle",
    strength: "10 x 50ml Bottles",
    batchNumber: "BN-2025-PF32",
    manufactureDate: "2025-02-28",
    expiryDate: "2027-04-30",
    purchasePrice: 180.00,
    sellingPrice: 265.00,
    stockQuantity: 14,
    minReorderLevel: 8,
    unit: "Box",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Beauty Aisle - Display",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-33",
    barcode: "60010010033",
    name: "Natrol Biotin 10,000 mcg Maximum Strength",
    genericName: "Biotin (Vitamin B7)",
    category: "Beauty Supplements",
    brand: "Natrol",
    dosageForm: "Tablet",
    strength: "100 Tablets",
    batchNumber: "BN-2025-NT33",
    manufactureDate: "2025-01-05",
    expiryDate: "2027-08-31",
    purchasePrice: 85.00,
    sellingPrice: 135.00,
    stockQuantity: 29,
    minReorderLevel: 10,
    unit: "Bottle",
    supplierId: "sup-gh-8",
    supplierName: "MediSource Ghana",
    locationRack: "Beauty Aisle - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 11. Antibiotics & Anti-Infectives
  {
    id: "med-gh-34",
    barcode: "60010010034",
    name: "Augmentin Tablets 1g",
    genericName: "Amoxicillin 875mg + Clavulanic Acid 125mg",
    category: "Antibiotics",
    brand: "GSK",
    dosageForm: "Tablet",
    strength: "14 Tablets",
    batchNumber: "BN-2026-AG34",
    manufactureDate: "2025-03-10",
    expiryDate: "2027-09-30",
    purchasePrice: 115.00,
    sellingPrice: 175.00,
    stockQuantity: 52,
    minReorderLevel: 20,
    unit: "Pack",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Dispensary Rack 1 - A",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-35",
    barcode: "60010010035",
    name: "Zithromax (Azithromycin) 500mg",
    genericName: "Azithromycin Monohydrate",
    category: "Antibiotics",
    brand: "Pfizer",
    dosageForm: "Tablet",
    strength: "3 Tablets",
    batchNumber: "BN-2025-ZT35",
    manufactureDate: "2025-02-15",
    expiryDate: "2027-06-30",
    purchasePrice: 70.00,
    sellingPrice: 110.00,
    stockQuantity: 35,
    minReorderLevel: 15,
    unit: "Pack",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Dispensary Rack 1 - B",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-36",
    barcode: "60010010036",
    name: "Cipro 500mg Tablets",
    genericName: "Ciprofloxacin Hydrochloride",
    category: "Antibiotics",
    brand: "Bayer",
    dosageForm: "Tablet",
    strength: "10 Tablets",
    batchNumber: "BN-2025-CP36",
    manufactureDate: "2024-12-01",
    expiryDate: "2027-02-28",
    purchasePrice: 45.00,
    sellingPrice: 70.00,
    stockQuantity: 41,
    minReorderLevel: 15,
    unit: "Pack",
    supplierId: "sup-gh-6",
    supplierName: "West Africa Pharma Wholesale",
    locationRack: "Dispensary Rack 1 - C",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-37",
    barcode: "60010010037",
    name: "Flagyl 400mg Tablets",
    genericName: "Metronidazole BP",
    category: "Antibiotics",
    brand: "Sanofi",
    dosageForm: "Tablet",
    strength: "20 Tablets",
    batchNumber: "BN-2025-FG37",
    manufactureDate: "2025-01-20",
    expiryDate: "2027-07-31",
    purchasePrice: 15.00,
    sellingPrice: 25.00,
    stockQuantity: 60,
    minReorderLevel: 20,
    unit: "Strip",
    supplierId: "sup-gh-6",
    supplierName: "West Africa Pharma Wholesale",
    locationRack: "Dispensary Rack 1 - D",
    isPrescriptionRequired: true,
    status: "In Stock"
  },

  // 12. Cardiovascular & Blood Pressure
  {
    id: "med-gh-38",
    barcode: "60010010038",
    name: "Amlodipine Tablets 10mg",
    genericName: "Amlodipine Besylate",
    category: "Cardiovascular",
    brand: "Teva",
    dosageForm: "Tablet",
    strength: "30 Tablets",
    batchNumber: "BN-2025-AM38",
    manufactureDate: "2025-03-01",
    expiryDate: "2028-02-28",
    purchasePrice: 28.00,
    sellingPrice: 45.00,
    stockQuantity: 58,
    minReorderLevel: 20,
    unit: "Box",
    supplierId: "sup-gh-6",
    supplierName: "West Africa Pharma Wholesale",
    locationRack: "Cardio Section - Rack A",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-39",
    barcode: "60010010039",
    name: "Cozaar (Losartan Potassium) 50mg",
    genericName: "Losartan Potassium",
    category: "Cardiovascular",
    brand: "MSD",
    dosageForm: "Tablet",
    strength: "28 Tablets",
    batchNumber: "BN-2025-CZ39",
    manufactureDate: "2025-02-14",
    expiryDate: "2027-05-31",
    purchasePrice: 65.00,
    sellingPrice: 105.00,
    stockQuantity: 32,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Cardio Section - Rack B",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-40",
    barcode: "60010010040",
    name: "Lipitor (Atorvastatin) 20mg",
    genericName: "Atorvastatin Calcium",
    category: "Cardiovascular",
    brand: "Viatris",
    dosageForm: "Tablet",
    strength: "30 Tablets",
    batchNumber: "BN-2025-LP40",
    manufactureDate: "2025-01-10",
    expiryDate: "2027-08-31",
    purchasePrice: 85.00,
    sellingPrice: 135.00,
    stockQuantity: 44,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Cardio Section - Rack C",
    isPrescriptionRequired: true,
    status: "In Stock"
  },

  // 13. Diabetes Care
  {
    id: "med-gh-41",
    barcode: "60010010041",
    name: "Glucophage XR 1000mg",
    genericName: "Metformin Extended Release",
    category: "Diabetes Care",
    brand: "Merck Serono",
    dosageForm: "Tablet",
    strength: "60 Tablets",
    batchNumber: "BN-2026-GP41",
    manufactureDate: "2025-04-05",
    expiryDate: "2028-03-31",
    purchasePrice: 75.00,
    sellingPrice: 120.00,
    stockQuantity: 68,
    minReorderLevel: 25,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Diabetes Section - Shelf 1",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-42",
    barcode: "60010010042",
    name: "Accu-Chek Instant Blood Glucose Test Strips",
    genericName: "Blood Glucose Test Strips",
    category: "Diabetes Care",
    brand: "Roche Diabetes",
    dosageForm: "Test Strips",
    strength: "50 Strips",
    batchNumber: "BN-2025-AC42",
    manufactureDate: "2025-02-20",
    expiryDate: "2027-01-31",
    purchasePrice: 110.00,
    sellingPrice: 165.00,
    stockQuantity: 28,
    minReorderLevel: 15,
    unit: "Pack",
    supplierId: "sup-gh-5",
    supplierName: "HealthLink Supplies",
    locationRack: "Diabetes Section - Diagnostics",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-43",
    barcode: "60010010043",
    name: "Lantus SoloStar Insulin Glargine 100U/ml",
    genericName: "Insulin Glargine rDNA",
    category: "Diabetes Care",
    brand: "Sanofi-Aventis",
    dosageForm: "Prefilled Pen",
    strength: "5 x 3ml Pens",
    batchNumber: "BN-2025-LS43",
    manufactureDate: "2025-03-01",
    expiryDate: "2027-02-28",
    purchasePrice: 320.00,
    sellingPrice: 480.00,
    stockQuantity: 12,
    minReorderLevel: 8,
    unit: "Pack",
    supplierId: "sup-gh-7",
    supplierName: "CarePoint Distributors",
    locationRack: "Cold Chain Refrigerator (2-8°C)",
    isPrescriptionRequired: true,
    status: "In Stock"
  },

  // 14. Gastrointestinal
  {
    id: "med-gh-44",
    barcode: "60010010044",
    name: "Nexium (Esomeprazole) 40mg",
    genericName: "Esomeprazole Magnesium",
    category: "Gastrointestinal",
    brand: "AstraZeneca",
    dosageForm: "Tablet",
    strength: "28 Tablets",
    batchNumber: "BN-2025-NX44",
    manufactureDate: "2025-02-18",
    expiryDate: "2027-08-31",
    purchasePrice: 95.00,
    sellingPrice: 150.00,
    stockQuantity: 36,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 10 - Shelf A",
    isPrescriptionRequired: true,
    status: "In Stock"
  },
  {
    id: "med-gh-45",
    barcode: "60010010045",
    name: "Gaviscon Double Action Liquid",
    genericName: "Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate",
    category: "Gastrointestinal",
    brand: "Reckitt",
    dosageForm: "Liquid",
    strength: "300ml",
    batchNumber: "BN-2025-GV45",
    manufactureDate: "2025-01-20",
    expiryDate: "2027-05-31",
    purchasePrice: 52.00,
    sellingPrice: 85.00,
    stockQuantity: 42,
    minReorderLevel: 15,
    unit: "Bottle",
    supplierId: "sup-gh-2",
    supplierName: "Ghana Health Supplies Ltd",
    locationRack: "Aisle 10 - Shelf B",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-46",
    barcode: "60010010046",
    name: "Buscopan Plus 10mg/500mg",
    genericName: "Hyoscine Butylbromide + Paracetamol",
    category: "Gastrointestinal",
    brand: "Sanofi",
    dosageForm: "Tablet",
    strength: "20 Tablets",
    batchNumber: "BN-2025-BP46",
    manufactureDate: "2025-03-05",
    expiryDate: "2027-07-31",
    purchasePrice: 38.00,
    sellingPrice: 62.00,
    stockQuantity: 45,
    minReorderLevel: 15,
    unit: "Box",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Aisle 10 - Shelf C",
    isPrescriptionRequired: false,
    status: "In Stock"
  },

  // 15. Eye & Ear Care
  {
    id: "med-gh-47",
    barcode: "60010010047",
    name: "Systane Ultra Lubricant Eye Drops",
    genericName: "Polyethylene Glycol 400 & Propylene Glycol",
    category: "Other",
    brand: "Alcon",
    dosageForm: "Drops",
    strength: "10ml",
    batchNumber: "BN-2025-SY47",
    manufactureDate: "2025-02-01",
    expiryDate: "2027-06-30",
    purchasePrice: 75.00,
    sellingPrice: 115.00,
    stockQuantity: 22,
    minReorderLevel: 10,
    unit: "Bottle",
    supplierId: "sup-gh-7",
    supplierName: "CarePoint Distributors",
    locationRack: "Aisle 11 - Eye Care",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-48",
    barcode: "60010010048",
    name: "Cerumol Ear Drops",
    genericName: "Chlorbutol in Oil Base",
    category: "Other",
    brand: "Thornton & Ross",
    dosageForm: "Drops",
    strength: "11ml",
    batchNumber: "BN-2024-CR48",
    manufactureDate: "2024-06-15",
    expiryDate: "2026-09-30", // Expiring soon
    purchasePrice: 35.00,
    sellingPrice: 58.00,
    stockQuantity: 6,
    minReorderLevel: 10,
    unit: "Bottle",
    supplierId: "sup-gh-7",
    supplierName: "CarePoint Distributors",
    locationRack: "Aisle 11 - Ear Care",
    isPrescriptionRequired: false,
    status: "Expiring Soon"
  },
  {
    id: "med-gh-49",
    barcode: "60010010049",
    name: "Artemether & Lumefantrine (Coartem 80/480mg)",
    genericName: "Artemether 80mg + Lumefantrine 480mg",
    category: "Antibiotics",
    brand: "Novartis",
    dosageForm: "Tablet",
    strength: "6 Tablets",
    batchNumber: "BN-2026-CT49",
    manufactureDate: "2025-04-10",
    expiryDate: "2028-02-28",
    purchasePrice: 28.00,
    sellingPrice: 48.00,
    stockQuantity: 110,
    minReorderLevel: 30,
    unit: "Pack",
    supplierId: "sup-gh-1",
    supplierName: "MedCare Distributors Ghana",
    locationRack: "Malaria Section - Shelf 1",
    isPrescriptionRequired: false,
    status: "In Stock"
  },
  {
    id: "med-gh-50",
    barcode: "60010010050",
    name: "Lonart DS Tablets",
    genericName: "Artemether 80mg + Lumefantrine 480mg",
    category: "Antibiotics",
    brand: "Bliss GVS Pharma",
    dosageForm: "Tablet",
    strength: "6 Tablets",
    batchNumber: "BN-2026-LN50",
    manufactureDate: "2025-03-25",
    expiryDate: "2027-12-31",
    purchasePrice: 24.00,
    sellingPrice: 40.00,
    stockQuantity: 95,
    minReorderLevel: 25,
    unit: "Pack",
    supplierId: "sup-gh-6",
    supplierName: "West Africa Pharma Wholesale",
    locationRack: "Malaria Section - Shelf 2",
    isPrescriptionRequired: false,
    status: "In Stock"
  }
];
